services:
  - name: flask-app
    type: web
    runtime: python
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
